IMG = {
    "img_1": {"label": "Real", "path": "img/img_1.png"},
    "img_2": {"label": "Sintetizada", "path": "img/img_2.jpg", "dif": "f"},
    "img_3": {"label": "Sintetizada", "path": "img/img_3.jpg", "dif": "m"},
    "img_4": {"label": "Sintetizada", "path": "img/img_4.jpg", "dif": "m"},
    "img_5": {"label": "Sintetizada", "path": "img/img_5.jpg", "dif": "f"},
    "img_6": {"label": "Real", "path": "img/img_6.png"},
    "img_7": {"label": "Real", "path": "img/img_7.png"},
    "img_8": {"label": "Real", "path": "img/img_8.png"},
    "img_9": {"label": "Real", "path": "img/img_9.png"},
    "img_10": {"label": "Real", "path": "img/img_10.png"},
    "img_11": {"label": "Real", "path": "img/img_11.png"},
    "img_12": {"label": "Real", "path": "img/img_12.png"},
    "img_13": {"label": "Real", "path": "img/img_13.png"},
    "img_14": {"label": "Real", "path": "img/img_14.png"},
    "img_15": {"label": "Real", "path": "img/img_15.png"},
    "img_16": {"label": "Real", "path": "img/img_16.png"},
    "img_17": {"label": "Real", "path": "img/img_17.png"},
    "img_18": {"label": "Real", "path": "img/img_18.png"},
    "img_19": {"label": "Sintetizada", "path": "img/img_19.jpg", "dif": "f"},
    "img_20": {"label": "Sintetizada", "path": "img/img_20.jpg", "dif": "f"},
    "img_21": {"label": "Sintetizada", "path": "img/img_21.jpg", "dif": "m"},
    "img_22": {"label": "Sintetizada", "path": "img/img_22.jpg", "dif": "m"},
    "img_23": {"label": "Sintetizada", "path": "img/img_23.jpg", "dif": "d"},
    "img_24": {"label": "Sintetizada", "path": "img/img_24.jpg", "dif": "d"},
    "img_25": {"label": "Real","path": "img/img_25.png"},
    "img_26": {"label": "Sintetizada", "path": "img/img_26.jpg", "dif": "m"},
    "img_27": {"label": "Real", "path": "img/img_27.png"},
    "img_28": {"label": "Real", "path": "img/img_28.png"},
    "img_29": {"label": "Real", "path": "img/img_29.png"},
    "img_30": {"label": "Sintetizada", "path": "img/img_30.jpg", "dif": "d"},
    "img_31": {"label": "Real", "path": "img/img_31.png"},
    "img_32": {"label": "Sintetizada", "path": "img/img_32.jpg", "dif": "f"},
    "img_33": {"label": "Sintetizada", "path": "img/img_33.jpg", "dif": "d"},
    "img_34": {"label": "Real", "path": "img/img_34.png"},
    "img_35": {"label": "Sintetizada", "path": "img/img_35.jpg", "dif": "m"},
    "img_36": {"label": "Real", "path": "img/img_36.png"} 
}